# Generated by Django 3.0.6 on 2020-07-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.CharField(default='00/00/00', max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='time',
            field=models.CharField(default='00:00', max_length=20),
        ),
    ]
