# Generated by Django 3.0.6 on 2020-07-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20200713_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='time',
        ),
    ]
