# Generated by Django 3.0.6 on 2020-07-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_record_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='subject',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
