# Generated by Django 3.0.6 on 2020-09-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_record_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='time',
            field=models.CharField(default='00:00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.CharField(default='00/00/00', max_length=12),
        ),
    ]
