# Generated by Django 3.0.6 on 2020-07-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200707_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='about',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='email',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='phone',
            field=models.CharField(default='0', max_length=13),
        ),
    ]
