# Generated by Django 3.0.6 on 2020-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200725_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='adminName',
        ),
        migrations.RemoveField(
            model_name='main',
            name='password',
        ),
        migrations.AddField(
            model_name='main',
            name='facebook',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='name',
            field=models.CharField(default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='set_name',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='twitter',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='youtube',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='phone',
            field=models.CharField(default='-', max_length=13),
        ),
    ]
