# Generated by Django 3.0.6 on 2020-08-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200810_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='aboutAdmin',
            field=models.TextField(default='-'),
        ),
    ]
