# Generated by Django 3.0.6 on 2020-07-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='Python(Static)', max_length=20),
        ),
    ]
