# Generated by Django 3.0.6 on 2020-07-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200717_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='osubid',
            field=models.IntegerField(default=0),
        ),
    ]
