# Generated by Django 3.0.6 on 2020-07-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200727_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='osubid',
        ),
    ]
