# Generated by Django 3.0.6 on 2020-07-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
