# Generated by Django 3.0.6 on 2020-07-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='count',
            field=models.CharField(max_length=20),
        ),
    ]
