# Generated by Django 3.0.6 on 2020-08-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='username',
            new_name='uname',
        ),
    ]
